/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_HelloRepeat */

#ifndef _Included_com_example_HelloRepeat
#define _Included_com_example_HelloRepeat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_HelloRepeat
 * Method:    helloRepeat
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_HelloRepeat_helloRepeat
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
